{{- $storageClass := .Values.backend.evidenceStorage.storageClass -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clio-evidence
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "clio.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backend.evidenceStorage.size }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass }}
  {{- end }}
